sudo: false
language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache:
  directories:
    - node_modules
branches:
  only:
    - master # build master branch only
before_script:
  - npm install -g hexo-cli
  - mkdir themes
  - git clone https://github.com/theme-next/hexo-theme-next themes/next
  - cd thems/next
  - git pull
  - npm install --production # 安装 主题的依赖
  - cd ../..
  - npm install
script:
  - hexo clean
  - hexo generate # generate static files
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: gh-pages
  local-dir: public