sudo: false
language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
before_install:
  - export TZ='Asia/Shanghai'
  - sed -i'' "s~https://github.com/vqianxiao/blog.git~https://${GH_TOKEN}@github.com/vqianxiao/blog.git~" _config.yml
branches:
  only:
    - master # build master branch only
script:
  - hexo generate # generate static files
  - hexo deploy
#after_script:
#  - cd ./public
#  - git init
#  - git config user.name "489305497@qq.com"
#  - git add .
#  - git commit -m "Travis CI Auto Builder at $(date +'%Y-%m-%d %H:%M:%S')"
#  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" gh-pages:gh-pages
#deploy:
#  provider: pages
#  skip-cleanup: true
#  github-token: $GH_TOKEN
#  keep-history: true
#  on:
#    branch: master
#  local-dir: public