sudo: false
language: node_js
node_js:
  - 16.2.0 # use nodejs v10 LTS
cache:
  directories:
    - node_modules
before_script:
  - npm install -g hexo-cli
  - mkdir themes
  - git clone https://github.com/theme-next/hexo-theme-next themes/next
branches:
  only:
    - master # build master branch only
script:
  - hexo clean
  - hexo generate # generate static files
  - hexo deploy
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: public